# NOTE: this file is generated via 'make generate'
dependencies:
  - go.mod
  - go.sum
  - vendor/**/*
documentation:
  - website/**/*
tooling:
  - internal/tools/**/*
service/key-vault:
  - internal/services/keyvault/**/*
